# Generated by Django 4.1.2 on 2023-07-04 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragavendra_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('userid', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 1, 16, 38, 81340)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='OrderStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Production', 'Production'), ('Out of Delivery', 'Out of Delivery'), ('completed', 'completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registerusers',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
