# Generated by Django 4.1.2 on 2023-07-25 06:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ragavendra_store', '0002_user_info_alter_orders_date_alter_orders_orderstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='zip_code',
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 23, 53, 8, 656847)),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('personal', 'Personal'), ('work', 'Work')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ragavendra_store.user_info')),
            ],
        ),
    ]
