# Generated by Django 4.1.2 on 2023-07-25 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragavendra_store', '0003_remove_user_info_address_remove_user_info_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Address_type',
            field=models.CharField(choices=[('home', 'Home'), ('personal', 'Personal'), ('work', 'Work')], default='Home', max_length=20),
        ),
        migrations.AddField(
            model_name='user_info',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 0, 17, 27, 668395)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
