# Generated by Django 4.1.2 on 2023-07-25 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragavendra_store', '0004_user_info_address_type_user_info_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 0, 23, 9, 404795)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Address_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
