# Generated by Django 4.1.2 on 2023-08-17 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragavendra_store', '0005_alter_orders_date_alter_user_info_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='Reciepentname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 4, 12, 41, 591139)),
        ),
    ]
