# Generated by Django 4.1.2 on 2023-08-17 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragavendra_store', '0006_user_info_reciepentname_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 4, 40, 44, 284771)),
        ),
    ]
